name: CI - VTC Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 2 * * *"   # tous les jours à 2h du matin

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: trafic
          POSTGRES_PASSWORD: trafic
          POSTGRES_DB: trafic
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt

    - name: Run pytest
      run: |
        pytest --cov=app --cov-report=xml --cov-report=term-missing

    - name: Run security checks
      run: bandit -r app

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        fail_ci_if_error: true

  load-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Load Test Dependencies
      run: |
        pip install locust
        pip install uvicorn

    - name: Run load test
      run: |
        uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        sleep 10
        locust -f tests/load/locustfile.py --headless -u 20 -r 5 -t 1m --host http://localhost:8000


